package info.projekt.database;
// Generated 2016-11-29 19:03:16 by Hibernate Tools 5.2.0.Beta1

/**
 * OrderDetails generated by hbm2java
 */
@SuppressWarnings("serial")
public class OrderDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer id;
	private Orders orders;
	private Products products;
	private double unitPrice;
	private short quantity;
	private float discount;

	public OrderDetails() {
	}

	public OrderDetails(Orders orders, Products products, double unitPrice, short quantity, float discount) {
		this.orders = orders;
		this.products = products;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.discount = discount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

}
