package info.projekt.database;
// Generated 2016-11-29 22:19:11 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

//import javafx.beans.property.IntegerProperty;
//import javafx.beans.property.StringProperty;

/**
 * Products generated by hbm2java
 */
@SuppressWarnings("serial")
public class Products implements java.io.Serializable {

	private Integer productId;
	private Categories categories;
	private Suppliers suppliers;
	private String productName;
	private String quantityPerUnit;
	private double unitPrice;
	private short unitsInStock;
	private short unitsOnOrder;
	private short reorderLevel;
	private String discontinued;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Products() {
	}

	public Products(Categories categories, Suppliers suppliers, String productName, String quantityPerUnit,
			double unitPrice, short unitsInStock, short unitsOnOrder, short reorderLevel, String discontinued) {
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.quantityPerUnit = quantityPerUnit;
		this.unitPrice = unitPrice;
		this.unitsInStock = unitsInStock;
		this.unitsOnOrder = unitsOnOrder;
		this.reorderLevel = reorderLevel;
		this.discontinued = discontinued;
	}

	public Products(Categories categories, Suppliers suppliers, String productName, String quantityPerUnit,
			double unitPrice, short unitsInStock, short unitsOnOrder, short reorderLevel, String discontinued,
			Set<OrderDetails> orderDetailses) {
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.quantityPerUnit = quantityPerUnit;
		this.unitPrice = unitPrice;
		this.unitsInStock = unitsInStock;
		this.unitsOnOrder = unitsOnOrder;
		this.reorderLevel = reorderLevel;
		this.discontinued = discontinued;
		this.orderDetailses = orderDetailses;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getQuantityPerUnit() {
		return this.quantityPerUnit;
	}

	public void setQuantityPerUnit(String quantityPerUnit) {
		this.quantityPerUnit = quantityPerUnit;
	}

	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public short getUnitsInStock() {
		return this.unitsInStock;
	}

	public void setUnitsInStock(short unitsInStock) {
		this.unitsInStock = unitsInStock;
	}

	public short getUnitsOnOrder() {
		return this.unitsOnOrder;
	}

	public void setUnitsOnOrder(short unitsOnOrder) {
		this.unitsOnOrder = unitsOnOrder;
	}

	public short getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(short reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	public String getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(String discontinued) {
		this.discontinued = discontinued;
	}

	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
